@api_url="http://localhost:3333"

POST {{api_url}}/trips
Content-type: application/json

{
  "destination": "Olimpia, Brasil",
  "starts_at": "2024-09-18T14:25:35.892Z",
  "ends_at": "2024-09-24T14:25:35.892Z",
  "emails_to_invite": ["evandroapaoliveira@gmail.com", "johndoe@acme.com"],
  "owner_name": "Evandro oliveira",
  "owner_email": "vandoaparecido@hotmail.com"
}

###

GET {{api_url}}/trips/283aa1ad-e21a-4246-aa04-5944f8ce0085/confirm
Content-type: application/json

###

PUT {{api_url}}/trips/283aa1ad-e21a-4246-aa04-5944f8ce0085

{
  "destination": "Florianópolis, Brasil",
  "starts_at": "2024-08-18T14:25:35.892Z",
  "ends_at": "2024-08-24T14:25:35.892Z"
}